import { Polygon_1, Polygon_2 } from "@/assets/icons";
import Hero from "./_home/hero";
import { LineBackground } from "@/assets/backgrounds";

export default function Home() {
  return (
    <main className="w-full">
      <Hero />
      page
      <div className="w-full overflow-hidden">
        <LineBackground />
        <div className="bg-green-500 inline-flex flex-wrap test px-3">
          {/* <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 />
          <Polygon_1 />
          <Polygon_2 /> */}
        </div>
      </div>
    </main>
  )
}
